name: Gerar APK Android

on:
  workflow_dispatch:

jobs:
  gerar-apk:
    runs-on: ubuntu-22.04

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk python3-pip \
            autoconf libtool pkg-config zlib1g-dev \
            libncurses5-dev libncursesw5-dev libtinfo5 \
            cmake libffi-dev libssl-dev

          python3 -m pip install --user buildozer Cython==0.29.34 virtualenv

      - name: Criar buildozer.spec
        run: |
          cat > buildozer.spec <<'EOF'
          [app]

          title = Consulta de Produtos

          package.name = consulta

          package.domain = com.i9mundotech

          source.dir = .

          source.include_exts = py,csv,png,jpg,jpeg,kv,atlas

          version = 1.0.0

          requirements = python3,kivy

          orientation = portrait

          fullscreen = 0

          android.api = 35

          android.minapi = 23

          android.ndk = 28c

          android.archs = arm64-v8a

          [buildozer]

          log_level = 2

          warn_on_root = 0
          EOF

      - name: Aceitar licenças Android
        run: |
          SDKMANAGER="$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager"

          yes | "$SDKMANAGER" --licenses || true

          "$SDKMANAGER" "platform-tools"
          "$SDKMANAGER" "platforms;android-35"
          "$SDKMANAGER" "build-tools;35.0.0"

      - name: Compilar APK
        run: |
          ~/.local/bin/buildozer -v android debug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: Consulta-de-Produtos-APK
          path: bin/*.apk
          retention-days: 7
